
import {Announcement} from './Announcement';

export const announcements: Announcement[] = [
  { id: 11, date : new Date(), author : 'Sébastien Martin', title: 'Dr Nice', content : 'Lorem ipsum dolor sit ametn viverra mattis varius.' },
  { id: 12, date : new Date(), author : 'Sébastien Martin', title: 'Narco' ,  content : 'Vestibulctum'},
  { id: 13, date : new Date(), author : 'Sébastien Martin', title: 'Bombasto' , content : 'Proin semper justo vel tincidunt lobortis. Phasellus eu nisi vehicula, interdum lectus in, interdum nisi. Donec semper congue nisi, sed laoreet magna rhoncus id. Fusce aliquet orci efficitur diam fringilla, sit amet tempor tortor euismod. Phasellus bibendum diam sed lorem consectetur pulvinar. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis consequat erat placerat enim vehicula iaculis ut vitae ipsum.'},
  { id: 14, date : new Date(), author : 'Sébastien Martin', title: 'Celeritas' , content : 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed scelerisque massa ac enim lacinia tincidunt. Aliquam cursus ex sit amet ligula pretium, sit amet iaculis felis posuere. Donec in vulputate justo, faucibus placerat sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse vitae felis vel metus auctor pretium quis commodo urna. Maecenas imperdiet purus nec leo ultricies vulputate. Duis in odio nibh. Proin sed lectus sed lacus tincidunt laoreet quis et velit. Sed posuere scelerisque venenatis. Ut sed tortor urna.'},
  { id: 15, date : new Date(), author : 'Sébastien Martin', title: 'Magneta', content : 'Donec finibus sagittis nunc eget luctus. Phasellus dapibus porttitor nulla, vitae ultricies nisl. Fusce cursus tellus sed ipsum pulvinar efficitur. Duis eu consectetur ligula. Nunc vestibulum ultricies tortor, eget vestibulum justo pulvinar molestie. Donec semper pellentesque velit, vitae gravida massa efficitur at. Nam aliquam vestibulum ultrices. Vivamus luctus dapibus lorem non vulputate. Aliquam in fringilla augue. Aenean nec efficitur felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam quis orci augue. Aenean velit quam, aliquet id nunc eget, aliquet cursus sapien. Suspendisse mollis non tellus at tincidunt.'},
  { id: 16, date : new Date(), author : 'Sébastien Martin', title: 'RubberMan' , content : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta neque magna, eu luctus lectus elementum eget. Integer porta, orci vel ' },
  { id: 17, date : new Date(), author : 'Sébastien Martin', title: 'Dynama' , content : 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla non urna vel ligula tincidunt euismod gravida' },
  { id: 18, date : new Date(), author : 'Sébastien Martin', title: 'Dr IQ' , content : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vulputate a quam id maximus. Maecenas sagittis auctor egestas. Aenean tempus.'},
  { id: 19, date : new Date(), author : 'Fleur Laurens',    title: 'Information du Ministère de la Nourriture', content : 'Mangez !' },
  { id: 20, date : new Date(), author : 'Sébastien Martin', title: 'Tornado', content :  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vulputate a quam id maximus. Maecenas sagittis auctor egestas. Aenean tempus.'}
 ];
